require("app.kod.Namespace")
require("app.kod.util.Time")
require("app.kod.util.String")

require("app.kod.util.Http")
require("app.kod.LoadCSBNode")
require("app.kod.ShaderHelper")
require("app.kod.GetTwoDimensionCode")

require("app.kod.diagnositic.Logger")
require("app.kod.diagnositic.Macro")

require("app.game.util.EventCenter")

-- 提前加载，网络层需要使用
require("app.config.GlobalConfig")
require("app.gameMode.config.MultiArea")

require("app.game.share.ShareConfig")
require("app.game.share.ShareWTF")

-- 道具加载
require("app.game.service.prop.PropReader")

-- 网络
require("app.net.core.ProtocolManager")
require("app.net.NetworkRequest")
require("app.net.NetworkResponse")
--require("app.net.UserDefinedRequest")
require("app.net.RequestManager")
require("app.net.WebProfileManager")

-- 协议
require("app.net.ProtocolCode")
require("app.net.protocol.Protocol_Auth")
require("app.net.protocol.Protocol_Activity")
require("app.net.protocol.Protocol_Chat")
require("app.net.protocol.Protocol_Game")
require("app.net.protocol.Protocol_Room")
require("app.net.protocol.Protocol_Battle")
require("app.net.protocol.Protocol_Marquee")
require("app.net.protocol.Protocol_Notice")
require("app.net.protocol.Protocol_Server")
require("app.net.protocol.Protocol_Club")
require("app.net.protocol.Protocol_League")
require("app.net.protocol.Protocol_Campaign")	
require("app.net.protocol.Protocol_MagicWindow")
require("app.net.protocol.Protocol_Push")
require("app.net.protocol.Protocol_Record")
require("app.net.protocol.Protocol_Gold")

-- 常量类往前面放
-- require("app.config.ChatConfig")
require("app.config.PropConfig")
require("app.config.UIConstants")
require("app.config.TurnCardConfig")
require("app.config.LuckyDrawConfig")
require("app.define.GlobalConst")
require("app.game.campaign.CampaignConfig")
require("app.config.WeekSignConfig")
require("app.config.NewShareConfig")
require("app.config.UrlConfig")
require("app.config.ConfigHelper")

require("app.kod.plugin.Runtime")
require("app.kod.plugin.Downloader")

require("app.manager.ServiceManager")
require("app.game.service.ConnectionService")
require("app.game.service.WaitingService")
require("app.game.service.LoginService")
require("app.game.service.LocalPlayerService")
require("app.game.service.RoomCreatorService")
require("app.game.service.RoomService")
require("app.game.service.UpdateService")
require("app.game.service.MarqueeService")
require("app.game.service.HistoryRecordService")
require("app.game.service.NoticeService")
require("app.game.service.ChatService")
require("app.game.service.FreePlayService")
require("app.game.service.MoneyTreeService")
require("app.game.service.ActivityService")
-- require("app.game.service.MagicWindowService")
require("app.game.service.WeChatService")
require("app.game.service.DingTalkService")
require("app.game.service.IAPService")
require("app.game.service.GetuiService")
require("app.game.service.RT_VoiceService")
require("app.game.service.MeiQiaService")
require("app.game.service.IM_VoiceService")
require("app.game.service.YVVoiceService")
require("app.game.service.DataEyeService")
require("app.game.service.AMapService")
require("app.game.service.TDAdTrackingService")
require("app.game.service.CertificationService")
require("app.game.service.JPushService")
require("app.game.service.PushService")
require("app.game.service.PaymentService")
require("app.game.service.prop.BackpackService")
require("app.game.service.HeadFrameService")
require("app.game.service.LocalPlayerSettingService")
require("app.game.service.TDGameAnalyticsService")
require("app.game.service.WebViewService")
require("app.game.service.AgentService")
require("app.game.service.RecordService")
require("app.game.service.MallService")
require("app.game.service.GiftService")
require("app.game.service.NoticeMailService")
require("app.game.service.GoldService")
require("app.game.service.GambleService")
require("app.game.service.LocalPushService")
require("app.game.service.friend.FriendService")
require("app.game.service.UploadLogService")
require("app.game.service.UserEventService")
require("app.game.service.club.ClubService")
require("app.game.service.bigLeague.BigLeagueService")
-- 活动 Service 的管理类
require("app.game.service.activity.ActivityServiceManager")

require("app.game.service.h5sdk.h5sdk")

--match
require("app.game.campaign.CampaignFSM")
require("app.game.campaign.CampaignService")

require("app.game.ui.UIMessageTipsMgr")
require("app.game.ui.UIMessageBox")
require("app.game.util.PlayerHeadIconUtil")
require("app.game.util.RequestHelper")
require("app.game.util.AgtDomainCheckerTCP") -- 替换为tcp的形式
require("app.game.util.PropTextConvertor")
require("app.game.util.GetShortUrl")

require("app.manager.LocalStorage")
require("app.manager.UIManager")
require("app.manager.GameFSM")
require("app.manager.AudioManager")
require("app.manager.RemoteFileManager")
require("app.manager.RedDotStateTreeManager")

require("app.kod.ObjectPool")
require("app.gameMode.mahjong.core.CardFactory")
require("app.game.service.prop.PropFactory")
require("app.gameMode.mahjong.GameService_Mahjong")
require("app.gameMode.mahjong.GameService_MahjongReplay")
require("app.gameMode.mahjong.Context")


require("app.game.GlobalSetting")

require("app.game.util.UISkipTool")
require("app.game.util.storageTools")
require("app.kod.VersionHelper")
require("app.game.util.commonUI.ShowUIWithBtnClose")

