---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanminhua.
--- DateTime: 2019/3/14 17:12
---

---@class GuideHelper
local GuideHelper = class("GuideHelper")

-- 把是否需要帮助的信息放到缓存中 目前到放到 Activity 一类中的

---@param key string 存储的键
---@param onePlayerMaxTimes number 在游戏没有被删除前总共要显示几次
function GuideHelper.isNeedGuide(key, onePlayerMaxTimes)
    key = tostring(key)
    if not key then
        return false
    end

    local ret = false
    local service = game.service.ActivityService.getInstance()
    service:loadLocalStorage()
    local cache = service.activeCache
    if cache then
        local data = cache[key] or 0
        if type(data) == 'string' then
            data = tonumber(data)
        end
        if data < onePlayerMaxTimes then
            ret = true
        end
        data = data + 1

        cache[key] = data
        service:saveData()
    end
    return ret
end

return GuideHelper