---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanminhua.
--- DateTime: 2019/3/14 15:05
---
local csbPath = "ui/csb/Guides/UIGuide_UIWallet_1.csb"
local UIBase = require("app.game.ui.UIBase")
local GuideBase = require("app.game.util.GuideBase")
local seekButton = require("app.game.util.UtilsFunctions").seekButton

---@class UIGuide_UIWallet_1:GuideBase
local UIGuide_UIWallet_1 = UIBase.buildUIClass("UIGuide_UIWallet_1 ", csbPath, GuideBase)
function UIGuide_UIWallet_1:ctor()
    GuideBase.ctor(self)
    UIBase.ctor(self)

    self._btnOk = seekButton(self, "Button_Ok", handler(self, self._onBtnOkClick))
end

function UIGuide_UIWallet_1:_onBtnOkClick(sender)
    self:hideSelf()
end

function UIGuide_UIWallet_1:getStrokeResPath()
    return "img/img_rect_green.png"
end

function UIGuide_UIWallet_1:getForegroundResPath()
    return "img/img_rect_mask.png"
end


return UIGuide_UIWallet_1