---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangyang.
--- DateTime: 2019/7/10 14:37
--- 点赞界面

local csbPath = "ui/csb/BigLeague/UIBigLeagueLikeTip.csb"
local super = require("app.game.ui.UIBase")

local UIBigLeagueLikeTip = class("UIBigLeagueLikeTip", super, function() return kod.LoadCSBNode(csbPath) end)

--[[    
        点赞确认界面
]]
function UIBigLeagueLikeTip:ctor()
end

function UIBigLeagueLikeTip:init()
   self._textMessage = seekNodeByName(self, "Text_Message", "ccui.Text")
   self._btnConfirm = seekNodeByName(self, "Button_Confirm", "ccui.Button")
   self._btnCancel = seekNodeByName(self, "Button_Cancel", "ccui.Button")
end

-- 点击事件注册
function UIBigLeagueLikeTip:_registerCallBack()
    bindEventCallBack(self._btnCancel,        handler(self, self._onBtnClose),        ccui.TouchEventType.ended)
    bindEventCallBack(self._btnConfirm,        handler(self, self._onBtnConfirm),        ccui.TouchEventType.ended)
end

function UIBigLeagueLikeTip:onShow(info , day)
    self._info = info
    self._day = day
    local str = "该团队团体总积分:%d分\n\n团队优胜分:%d\n\n活跃值:%.2f"
    str = string.format(str, math.round(info.allScore * 100) / 100, math.round(info.winScore * 100) / 100, math.round(info.fireScore * 100) / 100)
    self._textMessage:setString(str)

    self:_registerCallBack()
end

function UIBigLeagueLikeTip:_updateRank()
    self:_onCheckBoxGroupClick(self._btn_group, self._curTag)
end

function UIBigLeagueLikeTip:onHide()
end

function UIBigLeagueLikeTip:_onBtnConfirm()
    local service = game.service.bigLeague.BigLeagueService:getInstance()
    service:sendCCLClickLikeREQ(service:getLeagueData():getLeagueId(), self._info.clubId, game.service.TimeService:getInstance():getStartTime(self._day) * 1000,true)
end


function UIBigLeagueLikeTip:_onBtnClose()
    UIManager:getInstance():hide("UIBigLeagueLikeTip")
end

function UIBigLeagueLikeTip:needBlackMask()
    return true
end


return UIBigLeagueLikeTip